#!/bin/bash
PIN_ROOT=PIN/pin-3.17-98314-g0c048d619-gcc-linux
BENCH_BIN=benchmarks/bfs/bfs
PINTOOL=obj/obj-intel64/pintool.so

# convert trailing sizes to integers (k,M,G)
conv_pagesize() {
	case ${1: -1} in
		"k") ((res=${1%k} * 1024));;
		"M") ((res=${1%M} * 1024 * 1024));;
		"G") ((res=${1%G} * 1024 * 1024 * 1024));;
		*) res=$1;;
	esac
	echo $res;
}

let i=0
while [[ $i -lt 4 ]]; do
	let "i = $i + 1";
done

OTAG=$2;
[[ -z $OTAG ]] && OTAG="ndp_bfs_out";

TF="main"
FILTER_RTN="-filter_rtn do_work";
FILTER_SL="-filter_no_shared_libs"
PROBLEM_SIZE="200000 20"
#PROBLEM_SIZE="200 20"


echo "Starting BFS run using $1 ..."

while read line; do
	[[ ${line:0:1} == "#" ]] && continue
	l=($line);
	NM=${l[0]};
	NPT=${l[1]};
	P_SIZE=$(conv_pagesize ${l[2]});
	T_SIZE=${l[3]};
	OFIL="${OTAG}_${NM}_${NPT}.out";
	PIN_FLAGS="${FILTER_RTN} ${FILTER_SL} -o ${OFIL} -p ${P_SIZE} -tn ${T_SIZE} 
	-nm ${NM} -nt ${NPT}  -tf ${TF}";
	BFS_INPS="0 "$((NM*NPT))" ${PROBLEM_SIZE}";
	CMD="${PIN_ROOT}/pin -t ${PINTOOL} ${PIN_FLAGS} -- ${BENCH_BIN} ${BFS_INPS}";
	echo $CMD;
	$CMD > /dev/null;
done < $1
echo "Done !"
